version: '3.8'

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    environment:
      - HOST=db
      - USER=${ODOO_DB_USER}
      - PASSWORD=${ODOO_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8069 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - odoo-network
    restart: always  # Restart policy to ensure resilience

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${ODOO_DB_USER}
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD}
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${ODOO_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - odoo-network
    restart: always  # Restart policy to ensure resilience

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - odoo-network
    restart: always  # Restart policy to ensure resilience

volumes:
  odoo-web-data:
  odoo-db-data:

networks:
  odoo-network:
